[package]
name = "gatenative"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
static_init = "1.0"
libloading = "0.8"
gatesim = { path="../gatesim", version="0.1.0" }
gategen = { path="../gategen", version="0.1.0" }
gateutil = { path="../gateutil", version="0.1.0" }
