[package]
name = "gatenative"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
static_init = "1.0"
libloading = "0.8"
opencl3 = "0.9"
rayon = "1.0"
gatesim = { path="../gatesim", version="0.1.0" }
gate_calc_log_bits = { path="../gate_calc_log_bits", version="0.1.0" }
[dev-dependencies]
gateutil = { path="../gateutil", version="0.1.0" }
